name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: MeilCli/setup-crystal-action@v4
        with:
          crystal_version: 0.35.1
          shards_version: 0.11.1
      - name: Run Crystal
        env:
          BALENA_DEVICE_UUID: test
          PASSWORD: test
        run: |
          shards install && make test
